DECLARE @TableName NVARCHAR(128) = 'Test' 
SET NOCOUNT ON
SELECT [ROWText] FROM 
	(
	SELECT -1 AS Ord, '12.0' AS [ROWText]
		UNION 
	SELECT 0 AS Ord, CAST ((SELECT COUNT(*)
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = @TableName) AS VARCHAR(10)) AS [ROWText]
		UNION
	SELECT 
		ORDINAL_POSITION AS Ord,  CAST(ORDINAL_POSITION AS NVARCHAR) + ' SQLCHAR 0 '
		+ CASE 
			WHEN CHARACTER_MAXIMUM_LENGTH > 0 THEN CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR(20))
			ELSE '100'
		END
		+ ' '
		+ CASE 
			WHEN ORDINAL_POSITION = 1 THEN '"\""'
			WHEN ORDINAL_POSITION = (SELECT MAX(ORDINAL_POSITION) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @TableName) THEN '"\"\r\n"'
			ELSE '"\",\""'
		END 
		+ ' ' + QUOTENAME(COLUMN_NAME) + ' SQL_Latin1_General_CP1_CI_AS' + CHAR(13) + CHAR(10)
	FROM 
		INFORMATION_SCHEMA.COLUMNS
	WHERE 
		TABLE_NAME = @TableName
	) a
	ORDER BY Ord
